apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.app1.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.annotations.rewriteTarget }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:  
        - path: {{ .Values.app1.ingress.path }}
          pathType: {{ .Values.app1.ingress.pathType }}
          backend:
            service:
              name: {{ .Values.app1.name }}
              port:
                number: {{ .Values.app1.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.app2.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.annotations.rewriteTarget }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:  
        - path: {{ .Values.app2.ingress.path }}
          pathType: {{ .Values.app2.ingress.pathType }}
          backend:
            service:
              name: {{ .Values.app2.name }}
              port:
                number: {{ .Values.app2.service.port }}