apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app1.name }}
spec:
  ports:
  - port: {{ .Values.app1.service.port }}
  selector:
    app: {{ .Values.app1.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app2.name }}
spec:
  ports:
  - port: {{ .Values.app2.service.port }}
  selector:
    app: {{ .Values.app2.name }}
